apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  namespace: my-namespace
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: betrand1997/minikube-rancher-image
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
