apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  namespace: dev-namespace
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: betrand1999/self-hosted-image:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

