apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    replicas: 5
    matchLabels:
      app: mydeployment
  template:
    namespace: my-namespace
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: betrand1997/minikube-rancher-image
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

